# Generated by Django 5.2.5 on 2025-09-14 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('every_work_day', 'Every Work Day (Mon-Fri)'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly')], default='never', max_length=50)),
                ('frequency_total', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_exception', models.BooleanField(default=False)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='todo.scheduleseries')),
            ],
        ),
    ]
